package loader

import (
	pluginbadgerds "github.com/ipfs/go-ipfs/plugin/plugins/badgerds"
	plugincosmosds "github.com/ipfs/go-ipfs/plugin/plugins/cosmosds"
	pluginflatfs "github.com/ipfs/go-ipfs/plugin/plugins/flatfs"
	pluginipldgit "github.com/ipfs/go-ipfs/plugin/plugins/git"
	pluginlevelds "github.com/ipfs/go-ipfs/plugin/plugins/levelds"
	pluginipldiscn "github.com/likecoin/iscn-ipld/plugin"
)

// DO NOT EDIT THIS FILE
// This file is being generated as part of plugin build process
// To change it, modify the plugin/loader/preload.sh

func init() {
	Preload(pluginipldgit.Plugins...)
	Preload(pluginipldiscn.Plugins...)
	Preload(pluginbadgerds.Plugins...)
	Preload(pluginflatfs.Plugins...)
	Preload(pluginlevelds.Plugins...)
	Preload(plugincosmosds.Plugins...)
}
